import numpy as np
print(np.newaxis is None)
print(np.newaxis)
print('===========')

x = np.array([1, 2, 3])
print('x是：', x)
y = np.arange(3, 5)
print('y是：', y)
print('x.shape是：{} y.shape是：{}'.format(x.shape, y.shape))
print('维度扩充之后：None始终是1，是扩充的维度')
print('x[:, None].shape - {}'.format(x[:, None].shape))
print('x[None, :].shape - {}'.format(x[None, :].shape))
print('y[:, None].shape - {}'.format(y[:, None].shape))
print('y[None, :].shape - {}'.format(y[None, :].shape))
print('x[:, None]\n',x[:, None])

print(np.newaxis is None)
print(np.newaxis)
print('===========')
print('-------------------')
a = np.array([[1, 2], [1, 3]])
b = np.array([[2, 1], [3, 1]])

print(a)
print(b)
print(a@b)
print(np.dot(a,b))
print(np.matmul(a,b))
print(np.vdot(a,b))
print(np.outer(a,b))
# print(np.dot(a.reshape((1:-1),order='F')),reshape((1:-1),order='F')))
aa = a.reshape(-1,1)
bb = b.reshape(1,-1)
print(aa@bb)


print('cross')
print(np.cross(a,b))
print(a*b)
print(np.multiply(a,b))
print(np.tensordot(a,b))